# Generated by Django 4.1.2 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guild_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='discord_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
