# Generated by Django 4.1.2 on 2022-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_account_id_remove_guild_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='role_core_id',
            field=models.CharField(max_length=30),
        ),
    ]
